//@ui5-bundle project_d/Component-preload.js
sap.ui.predefine("project_d/Component", ["sap/ui/core/UIComponent","sap/ui/model/json/JSONModel"],(e,t)=>{"use strict";return e.extend("project_d.Component",{metadata:{interfaces:["sap.ui.core.IAsyncContentCreation"],manifest:"json"},init(){e.prototype.init.apply(this,arguments);const n={recipient:{name:"Name",do:"Press here"}};const o=new t(n);this.setModel(o)}})});
sap.ui.predefine("project_d/controller/App.controller", ["sap/ui/core/mvc/Controller"],e=>{"use strict";return e.extend("project_d.controller.App",{})});
sap.ui.predefine("project_d/controller/HelloPanel.controller", ["sap/ui/core/mvc/Controller","sap/m/MessageToast","project_d/model/Helpers"],(e,o,t)=>{"use strict";return e.extend("project_d.controller.HelloPanel",{onInit(){this.oDialog=null},onShowHello(){const e=this.getView();const t=e.getModel();const l=e.getModel("i18n").getResourceBundle();const n=t.getProperty("/recipient/name");const s=l.getText("buttonTextsMsg",[n]);o.show(s)},formatting(e,...o){return t.formatting(e,...o)},async onOpenDialog(){this.oDialog??=await this.loadFragment({name:"project_d.view.HelloDialog"});this.oDialog.open()},onCloseDialog(){this.byId("helloDialog").close()}})});
sap.ui.predefine("project_d/controller/InvoiceList.controller", ["sap/ui/core/mvc/Controller","sap/ui/model/json/JSONModel"],function(e,n){"use strict";return e.extend("project_d.controller.InvoiceList",{onInit(){const e=new n({currency:"EUR"});this.getView().setModel(e,"view")}})});
sap.ui.predefine("project_d/model/CurrencyStatus", [],()=>{"use strict";return{statusText(e){const t=this.getOwnerComponent().getModel("i18n").getResourceBundle();switch(e){case"A":return t.getText("invoiceStatusA");case"B":return t.getText("invoiceStatusB");case"C":return t.getText("invoiceStatusC");default:return e}}}});
sap.ui.predefine("project_d/model/Helpers", [],()=>{"use strict";return{formatting(e,...t){return typeof e==="string"?e.replace(/{(\d+)}/g,(e,r)=>typeof t[r]!=="undefined"?t[r]:e):""}}});
sap.ui.require.preload({
	"project_d/i18n/i18n.properties":'# App Descriptor\nappTitle=Title Hello World\nappDescription=A simple walkthrough app that explains the most important concepts of SAPUI5\n\n# Hello Panel\nhomePageTitle=The Home Title\nhomePaneTitle=The Home Panel Title\nhelloPanelTitle=The Hello Panel Title\ninputPlaceholder=Enter here\ninputDescription=it was written: {0}\nbuttonText={0}\nbuttonTextsMsg=Hello {0}\nopenDialogButtonText=Open Dialog\ndialogCloseButtonText=Close\n\n# Invoice List\ninvoiceListTitle=Invoices\ninvoiceStatusA=New\ninvoiceStatusB=In Progress\ninvoiceStatusC=Done',
	"project_d/manifest.json":'{"_version":"1.65.0","sap.app":{"id":"project_d","i18n":{"bundleUrl":"i18n/i18n.properties","supportedLocales":[""],"fallbackLocale":""},"title":"{{appTitle}}","description":"{{appDescription}}","type":"application","applicationVersion":{"version":"1.0.0"}},"sap.ui":{"technology":"UI5","deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"dependencies":{"minUI5Version":"1.108.0","libs":{"sap.ui.core":{},"sap.m":{}}},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"project_d.i18n.i18n","supportedLocales":[""],"fallbackLocale":""}},"invoice":{"type":"sap.ui.model.json.JSONModel","uri":"data/Invoices.json"}},"rootView":{"viewName":"project_d.view.App","type":"XML","async":true,"id":"app"},"resources":{"css":[{"uri":"css/style.css"}]}}}',
	"project_d/view/App.view.xml":'<mvc:View\n    controllerName="project_d.controller.App"\n    xmlns="sap.m"\n    xmlns:mvc="sap.ui.core.mvc"\n    displayBlock="true"\n><Shell><App class="myAppDemoWT"><pages><Page title="{i18n>homePageTitle}"><content><Panel\n                            headerText="{i18n>helloPanelTitle}"\n                            class="sapUiResponsiveMargin"\n                            width="auto"\n                        ><content><mvc:XMLView\n                                    viewName="project_d.view.HelloPanel"\n                                /><mvc:XMLView\n                                    viewName="project_d.view.InvoiceList"\n                                /></content></Panel></content></Page></pages></App></Shell></mvc:View>\n',
	"project_d/view/HelloDialog.fragment.xml":'<c:FragmentDefinition\n    xmlns="sap.m"\n    xmlns:c="sap.ui.core"\n><Dialog\n        id="helloDialog"\n        title="Hello {/recipient/name} in Dialog"\n    ><content><c:Icon\n                src="sap-icon://hello-world"\n                size="8rem"\n                class="sapUiMediumMargin"\n            /></content><endButton><Button\n                text="1 {i18n>dialogCloseButtonText} end"\n                icon="sap-icon://decline"\n                press=".onCloseDialog"\n            /></endButton><beginButton><Button\n                text="2 {i18n>dialogCloseButtonText} begin"\n                icon="sap-icon://accept"\n                press=".onCloseDialog"\n            /></beginButton></Dialog></c:FragmentDefinition>\n',
	"project_d/view/HelloPanel.view.xml":'<mvc:View\n    controllerName="project_d.controller.HelloPanel"\n    xmlns="sap.m"\n    xmlns:mvc="sap.ui.core.mvc"\n><Panel\n        headerText="{i18n>homePaneTitle}"\n        class="sapUiResponsiveMargin"\n        width="auto"\n    ><content><Button\n                id="helloDialogButton"\n                icon="sap-icon://action"\n                text="{i18n>openDialogButtonText}"\n                press=".onOpenDialog"\n                class="sapUiSmallMarginEnd myCustomButton"\n            /><Button\n                text="{= ${i18n>buttonText}.replaceAll(\'{0}\', ${/recipient/do}) }"\n                icon="sap-icon://activate"\n                press=".onShowHello"\n                class="sapUiSmallMarginEnd myCustomButton"\n            /><Input\n                value="{/recipient/name}"\n                placeholder="{i18n>inputPlaceholder}"\n                valueLiveUpdate="true"\n                width="60%"\n            /><FormattedText\n                htmlText="{\n                    parts: [\'i18n>inputDescription\', \'/recipient/name\'],\n                    formatter: \'.formatting\'\n                }"\n                class="sapUiSmallMargin sapThemeHightlight-asColor myCustomText"\n            /></content></Panel></mvc:View>\n',
	"project_d/view/InvoiceList.view.xml":'<mvc:View\n    controllerName="project_d.controller.InvoiceList"\n    xmlns="sap.m"\n    xmlns:core="sap.ui.core"\n    xmlns:mvc="sap.ui.core.mvc"\n><List\n        headerText="{i18n>invoiceListTitle}"\n        class="sapUiResponsiveMargin"\n        width="auto"\n        items="{invoice>/Invoices}"\n    ><items><ObjectListItem\n                core:require="{\n\t\t\t\t\tCurrency: \'sap/ui/model/type/Currency\'\n\t\t\t\t}"\n                title="{invoice>Quantity} x {invoice>ProductName}"\n                number="{\n\t\t\t\t\tparts: [\n\t\t\t\t\t\t\'invoice>ExtendedPrice\',\n\t\t\t\t\t\t\'view>/currency\'\n\t\t\t\t\t],\n\t\t\t\t\ttype: \'Currency\',\n\t\t\t\t\tformatOptions: {\n\t\t\t\t\t\tshowMeasure: false\n\t\t\t\t\t}\n\t\t\t\t}"\n                numberUnit="{view>/currency}"\n                numberState="{= ${invoice>ExtendedPrice} > 50 ? \'Error\' : ${invoice>ExtendedPrice} > 9 ? \'Warning\' : ${invoice>ExtendedPrice} > 8 ? \'Success\' : ${invoice>ExtendedPrice} &lt; 3 ?  \'None\' : \'Information\' }"\n            ><firstStatus><ObjectStatus\n                        core:require="{\n\t\t\t\t\t\t\tCurrencyStatus: \'project_d/model/CurrencyStatus\'\n\t\t\t\t\t\t}"\n                        text="{\n\t\t\t\t\t\t\tpath: \'invoice>Status\',\n\t\t\t\t\t\t\tformatter: \'CurrencyStatus.statusText.bind($controller)\'\n\t\t\t\t\t\t}"\n                    /></firstStatus></ObjectListItem></items></List></mvc:View>\n'
});
//# sourceMappingURL=Component-preload.js.map
