# OVERRIDE - DEVELOPMENT
services:
  nginx:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:ro,cached
      - ./.docker/nginx/conf.d/default-dev.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      php:
        condition: service_healthy
      vite:
        condition: service_started
      db:
        condition: service_healthy
  php:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: dev
    environment:
      IS_DEV: "true"
      XDEBUG_MODE: "develop,debug"
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003"
    volumes:
      - .:/var/www/html:cached
      - ~/.composer/cache:/root/.composer/cache
      - php_logs:/var/log/php

  db:
    ports:
      - "${DB_PORT:-5432}:5432"

  vite:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: vite
    working_dir: /app
    ports:
      - "${VITE_PORT:-5173}:5173"
    networks:
      - app-network
    volumes:
      - .:/app:cached
      - ./.cache:/app/.cache
      - vite_node_modules:/app/node_modules
    restart: unless-stopped

volumes:
  vite_node_modules:
  nginx_logs:
  php_logs: