services:
  nginx:
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
      args:
        NGINX_ENV: prod
    ports:
      - "80:80"
      - "443:443" # Expose HTTPS port for production
    volumes:
      - .:/var/www/html:ro,cached
      - ./.docker/nginx/conf.d/default-prod.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx-logs:/var/log/nginx
      - nginx-cache:/var/cache/nginx
    depends_on:
      php:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "nginx -t" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s

  php:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
      - php-fpm-socket:/var/run/php-fpm
      - php-logs:/var/log/php
    networks:
      - app-network
    restart: always
    env_file:
      - ./.env
    environment:
      IS_DEV: "false"
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d/"
    healthcheck:
      test: [ "CMD", "php-fpm", "-t" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  app-network:
    driver: bridge

volumes:
  php-fpm-socket:
  php-logs:
  nginx-cache:
  nginx-logs: