# OVERRIDE - DEVELOPMENT
services:
  nginx:
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:cached
      - ./.docker/nginx/conf.d/default-dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      php:
        condition: service_healthy
      vite:
        condition: service_started
      db:
        condition: service_healthy
  php:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: dev
    environment:
      IS_DEV: "true"
    volumes:
      - .:/var/www/html:cached
      - php_logs:/var/log/php
      - ~/.composer/cache:/root/.composer/cache

  db:
    ports:
      - "${DB_PORT:-5432}:5432"

  vite:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: vite
    working_dir: /app
    ports:
      - "${VITE_PORT:-5173}:5173"
    networks:
      - app-network
    volumes:
      - .:/app:cached
      - ./.cache:/app/.cache
      - vite_node_modules:/app/node_modules
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    networks:
      - app-network

volumes:
  vite_node_modules:
  nginx_logs:
  php_logs: