services:
  nginx:
    build:
      args:
        NGINX_ENV: dev
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html:ro,cached
      - ./.docker/nginx/conf.d/default-dev.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx-logs:/var/log/nginx
      - nginx-cache:/var/cache/nginx
    depends_on:
      php:
        condition: service_healthy
      vite:
        condition: service_started
    restart: unless-stopped

  php:
    environment:
      IS_DEV: "true"
    volumes:
      - ./:/var/www/html:delegated
      - php-fpm-socket:/var/run/php-fpm
      - php-logs:/var/log/php
    restart: unless-stopped

  vite:
    build:
      context: .
      dockerfile: .docker/vite/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app:delegated
      - /app/node_modules
    working_dir: /app
    command: npm run dev # Start Vite dev server
    networks:
      - app-network
    restart: unless-stopped
    environment:
      VITE_HOST: 0.0.0.0
      VITE_PORT: 5173