services:
  nginx:
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html:ro,cached
      - nginx_logs:/var/log/nginx
      - ./.docker/nginx/conf.d/default-dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      php:
        condition: service_healthy
      vite:
        condition: service_started

  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile-dev
    environment:
      IS_DEV: "true"
    volumes:
      - .:/var/www/html:cached
      - php_logs:/var/log/php

  vite:
    build:
      context: .
      dockerfile: .docker/vite/Dockerfile
    working_dir: /app
    ports:
      - "5173:5173"
    networks:
      - app-network
    volumes:
      - .:/app:cached
      - ./.cache:/app/.cache
      - vite_node_modules:/app/node_modules
    restart: unless-stopped

volumes:
  vite_node_modules: