services:
  gh-pages:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile-dev
    volumes:
      - .:/app
      - ./static:/app/static
    environment:
      IS_DEV: "false"
    networks:
      - app-network

  vite-builder:
    build:
      context: .
      dockerfile: .docker/vite/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - ./.cache:/app/.cache
      - vite_node_modules:/app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  vite_node_modules: