services:
  nginx:
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html:ro,cached
      - nginx_logs:/var/log/nginx
      - ./.docker/nginx/conf.d/default-dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      php:
        condition: service_healthy
      vite:
        condition: service_started
      db: # dependency on db
        condition: service_healthy

  php:
    environment:
      IS_DEV: "true"
      # Database connection variables for develop
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: myapp_db
      DB_USERNAME: myuser
      DB_PASSWORD: mypassword
    volumes:
      - .:/var/www/html:cached
      - php_logs:/var/log/php
      - vendor_data:/var/www/html/vendor # Ensure PHP dependencies are in a Docker volume
    depends_on:
      db:
        condition: service_healthy # Ensure DB is ready before PHP starts

  vite:
    build:
      context: .
      dockerfile: .docker/vite/Dockerfile
    working_dir: /app
    ports:
      - "5173:5173"
    networks:
      - app-network
    volumes:
      - .:/app:cached
      - ./.cache:/app/.cache
      - vite_node_modules:/app/node_modules
    restart: unless-stopped

  # Database service for development
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: myapp_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Expose port on host for PhpStorm connection
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  vite_node_modules:
  vendor_data:
  db_data: